arb-dir: lib/l10n
template-arb-file: app_en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
synthetic-package: false
preferred-supported-locales: 'en'
use-deferred-loading: false