name: pokemon_app
description: A simple project for pokemon info.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Dart packages
  collection: ^1.16.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  dio: ^4.0.1
  http: ^0.13.5
  intl: ^0.17.0

  #Flutter packages
  flutter_bloc: ^8.0.0

  #Platform plugins
  path: ^1.8.1
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.10.0
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito:
  mocktail:
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21